version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: emr_data_pipeline
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: EMR_DATA
    volumes:
      -  postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:

